name: shikidev
description: Unofficial application for shikimori.me
publish_to: 'none'

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number is used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
# In Windows, build-name is used as the major, minor, and patch parts
# of the product and file versions while build-number is used as the build suffix.
version: 0.4.0+36

environment:
  sdk: '>=3.0.0 <4.0.0'
  #sdk: '>=3.1.0-63.1.beta <4.0.0'

isar_version: &isar_version 3.1.0+1

dependencies:
  audio_video_progress_bar: ^1.0.1
  #git_info: ^1.1.2
  bottom_sheet: ^3.1.2
  cached_network_image: ^3.2.3
  collection: ^1.17.1
  connectivity_plus: ^4.0.1
  dart_discord_rpc:
    git:
      url: https://github.com/alexmercerind/dart_discord_rpc.git
      ref: 48a15a750d9ee50c521a408c466bd681321a38e2
  device_info_plus: ^9.0.2
  dio: ^5.3.0
  dio_smart_retry: ^5.0.0
  dismissible_page: ^1.0.2
  #double_tap_player_view: ^2.0.3
  dynamic_color: ^1.6.6
  easy_image_viewer: ^1.2.1
  equatable: ^2.0.5
  expandable_text: ^2.3.0
  file_picker: ^5.3.3
  flutter:
    sdk: flutter
  flutter_animate: ^4.2.0+1
  flutter_bbcode: ^1.4.1
  flutter_cache_manager: ^3.3.1
  flutter_hooks: ^0.20.0
  flutter_html: ^3.0.0-beta.2
  flutter_markdown: ^0.6.17
  flutter_secure_storage: ^8.0.0
  #flutter_displaymode: ^0.6.0
  flutter_web_auth: ^0.5.0
  freezed_annotation: ^2.4.1
  go_router: 7.1.1
  hooks_riverpod: ^2.3.7
  html: ^0.15.4
  http: ^1.1.0
  infinite_scroll_pagination: ^3.2.0
  #yaml: ^3.1.1
  intl: ^0.18.1
  isar: *isar_version
  isar_flutter_libs: *isar_version
  loggy: ^2.0.3
  media_kit: ^1.1.2+1
  media_kit_libs_windows_video: ^1.0.5
  #media_kit_native_event_loop: ^1.0.6
  media_kit_video: ^1.1.2
  #nirikshak: ^0.1.0
  network_logger:
    git:
      url: https://github.com/themisir/flutter-network-logger.git
      ref: master # branch name
  package_info_plus: ^4.0.2
  path: ^1.8.2
  path_provider: ^2.0.15
  permission_handler: ^10.4.3
  #native_dio_adapter: ^0.1.0
  pretty_dio_logger: ^1.3.1
  sentry_dio: ^7.9.0
  #copy_with_extension: ^5.0.2
  sentry_flutter: ^7.9.0
  share_plus: ^7.0.2
  shared_preferences: ^2.2.0
  shimmer: ^3.0.0
  sliver_tools: ^0.2.12
  synchronized: ^3.1.0
  timeago: ^3.5.0
  tinycolor2: ^3.0.1
  url_launcher: ^6.1.11
  version: ^3.0.2
  video_player: ^2.7.0
  wakelock_plus: ^1.1.1
  window_manager: ^0.3.5

dev_dependencies:
  build_runner: ^2.4.6
  #copy_with_extension_gen: ^5.0.3
  flutter_lints: ^2.0.2
  freezed: ^2.4.1
  isar_generator: *isar_version

flutter:
  uses-material-design: true
  # assets:
  # - assets/shiki-studios-filtered-sorted.json
  # - .git/
  # - .git/refs/heads/
  # To add assets to your application, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg
  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware
  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages
  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example: SourceSansPro-Bold
  # fonts:
  #   - family: SourceSansPro
  #     fonts:
  #       - asset: assets/fonts/SourceSansPro-Regular.ttf
  #       - asset: assets/fonts/SourceSansPro-Italic.ttf
  #         style: italic
  #       - asset: assets/fonts/SourceSansPro-Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages

# Task definition for derry
scripts: derry.yaml
