name: shikidev
description: Unofficial application for shikimori.me
publish_to: 'none'

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number is used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
# In Windows, build-name is used as the major, minor, and patch parts
# of the product and file versions while build-number is used as the build suffix.
version: 0.0.2+7

environment:
  sdk: '>=2.19.4 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

  # new dep
  version: ^3.0.2
  git_info: ^1.1.2
  bottom_sheet: ^3.1.2
  infinite_scroll_pagination: ^3.2.0
  
  #desktop
  window_manager: ^0.3.1
  path: ^1.8.2
  media_kit: ^0.0.2
  media_kit_video: ^0.0.2
  media_kit_libs_windows_video: ^1.0.1
  #super_clipboard: ^0.3.0+1
  dart_discord_rpc:
    git:
      url: https://github.com/alexmercerind/dart_discord_rpc.git
      ref: 48a15a750d9ee50c521a408c466bd681321a38e2
  
  #storage
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  isar: ^3.0.5
  isar_flutter_libs: ^3.0.5
  shared_preferences: ^2.0.20
  flutter_secure_storage: ^8.0.0

  #network
  http: ^0.13.5
  connectivity_plus: ^3.0.3
  dio: ^5.0.2
  dio_smart_retry: ^5.0.0
  #native_dio_adapter: ^0.1.0
  pretty_dio_logger: ^1.3.1
  #nirikshak: ^0.1.0
  network_logger:
    git:
      url: https://github.com/themisir/flutter-network-logger.git
      ref: master # branch name
  
  go_router:
    path: external/go_router
  yaml: ^3.1.1
  intl: ^0.18.0
  collection: ^1.17.0
  path_provider: ^2.0.14
  equatable: ^2.0.5
  material_color_utilities: ^0.2.0
  dynamic_color: ^1.6.2
  flutter_displaymode: ^0.5.0
  flutter_web_auth: ^0.5.0
  url_launcher: ^6.1.10
  hooks_riverpod: ^2.3.2
  flutter_hooks: ^0.18.6
  shimmer: ^2.0.0
  sliver_tools: ^0.2.9
  tinycolor2: ^3.0.1
  expandable_text: ^2.3.0
  flutter_html: ^3.0.0-alpha.6
  html: ^0.15.2
  extended_image: ^7.0.2
  package_info_plus: ^3.0.3
  share_plus: ^6.3.2

  video_player: ^2.6.0
  wakelock: ^0.6.2
  audio_video_progress_bar: ^1.0.0

  #copy_with_extension: ^5.0.2

  #appmetrica_plugin: ^1.1.0
  sentry_flutter: ^7.4.2
  sentry_dio: ^7.4.2
  loggy: ^2.0.3

dev_dependencies:
  flutter_lints: ^2.0.0

  build_runner: ^2.3.3
  hive_generator: ^2.0.0
  isar_generator: ^3.0.5
  copy_with_extension_gen: ^5.0.2

flutter:
  uses-material-design: true

  assets:
  - assets/shiki-studios-filtered-sorted.json
  - .git/
  - .git/refs/heads/

  # To add assets to your application, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example: SourceSansPro-Bold
  # fonts:
  #   - family: SourceSansPro
  #     fonts:
  #       - asset: assets/fonts/SourceSansPro-Regular.ttf
  #       - asset: assets/fonts/SourceSansPro-Italic.ttf
  #         style: italic
  #       - asset: assets/fonts/SourceSansPro-Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages

# Task definition for derry
scripts: derry.yaml