name: shikidev
description: Unofficial application for shikimori.me
publish_to: 'none'

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number is used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
# In Windows, build-name is used as the major, minor, and patch parts
# of the product and file versions while build-number is used as the build suffix.
version: 0.0.5+14

environment:
  #sdk: '>=3.0.0 <4.0.0'
  sdk: '>=3.1.0-63.1.beta <4.0.0'

isar_version: &isar_version 3.1.0+1

dependencies:
  flutter:
    sdk: flutter

  # new dep
  version: ^3.0.2
  #git_info: ^1.1.2
  bottom_sheet: ^3.1.2
  infinite_scroll_pagination: ^3.2.0
  flutter_bbcode: ^1.4.1
  
  #desktop
  window_manager: ^0.3.4
  path: ^1.8.2
  media_kit: ^0.0.7+1
  media_kit_video: ^0.0.9
  media_kit_native_event_loop: ^1.0.3
  media_kit_libs_windows_video: ^1.0.2
  dart_discord_rpc:
    git:
      url: https://github.com/alexmercerind/dart_discord_rpc.git
      ref: 48a15a750d9ee50c521a408c466bd681321a38e2
  
  #storage
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  isar: *isar_version
  isar_flutter_libs: *isar_version
  shared_preferences: ^2.1.1
  flutter_secure_storage: ^8.0.0

  #network
  http: ^0.13.5
  connectivity_plus: ^4.0.1
  dio: ^5.0.2
  dio_smart_retry: ^5.0.0
  #native_dio_adapter: ^0.1.0
  pretty_dio_logger: ^1.3.1
  #nirikshak: ^0.1.0
  network_logger:
    git:
      url: https://github.com/themisir/flutter-network-logger.git
      ref: master # branch name
  
  go_router:
    path: external/go_router
  #yaml: ^3.1.1
  intl: ^0.18.1
  collection: ^1.17.1
  path_provider: ^2.0.15
  equatable: ^2.0.5
  dynamic_color: ^1.6.5
  #flutter_displaymode: ^0.6.0
  flutter_web_auth: ^0.5.0
  url_launcher: ^6.1.11
  hooks_riverpod: ^2.3.6
  flutter_hooks: ^0.18.6
  shimmer: ^3.0.0
  sliver_tools: ^0.2.10
  tinycolor2: ^3.0.1
  expandable_text: ^2.3.0
  flutter_html: ^3.0.0-beta.1
  html: ^0.15.2
  #extended_image: ^8.0.1
  package_info_plus: ^3.0.3
  device_info_plus: ^8.2.1
  share_plus: ^6.3.4
  
  #transparent_image: ^2.0.1
  cached_network_image: ^3.2.3
  flutter_cache_manager: ^3.3.0

  video_player: ^2.6.1
  wakelock: ^0.6.2
  audio_video_progress_bar: ^1.0.1

  #copy_with_extension: ^5.0.2

  #appmetrica_plugin: ^1.1.0
  sentry_flutter: ^7.6.1
  sentry_dio: ^7.6.1
  loggy: ^2.0.3

dev_dependencies:
  flutter_lints: ^2.0.0

  build_runner: ^2.4.4
  hive_generator: ^2.0.0
  isar_generator: *isar_version
  copy_with_extension_gen: ^5.0.2

flutter:
  uses-material-design: true

  # assets:
  # - assets/shiki-studios-filtered-sorted.json
  # - .git/
  # - .git/refs/heads/

  # To add assets to your application, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example: SourceSansPro-Bold
  # fonts:
  #   - family: SourceSansPro
  #     fonts:
  #       - asset: assets/fonts/SourceSansPro-Regular.ttf
  #       - asset: assets/fonts/SourceSansPro-Italic.ttf
  #         style: italic
  #       - asset: assets/fonts/SourceSansPro-Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages

# Task definition for derry
scripts: derry.yaml