name: shikidev
description: Unofficial application for shikimori
publish_to: 'none'

version: 0.8.1+52

environment:
  sdk: '>=3.0.0 <4.0.0'
  flutter: '>=3.16.0'

isar_version: &isar_version 3.1.0+1

dependencies:
  audio_video_progress_bar: ^2.0.1
  #git_info: ^1.1.2
  #bottom_sheet: ^3.1.2
  cached_network_image: ^3.3.0
  collection: ^1.17.1
  connectivity_plus: ^5.0.1
  dart_discord_rpc:
    git:
      url: https://github.com/alexmercerind/dart_discord_rpc.git
      ref: 48a15a750d9ee50c521a408c466bd681321a38e2
  device_info_plus: ^9.0.2
  dio: ^5.3.3
  dio_smart_retry: ^6.0.0
  dismissible_page: ^1.0.2
  dynamic_color: ^1.6.8
  easy_image_viewer: ^1.2.1
  equatable: ^2.0.5
  expandable_text: ^2.3.0
  file_picker: ^5.5.0
  flutter:
    sdk: flutter
  flutter_animate: ^4.2.0+1
  flutter_bbcode: ^1.4.1
  flutter_cache_manager: ^3.3.1
  flutter_hooks: ^0.20.3
  flutter_html: ^3.0.0-beta.2
  flutter_markdown: ^0.6.18
  flutter_rating_bar: ^4.0.1
  flutter_secure_storage: ^9.0.0
  flutter_web_auth: ^0.5.0
  font_awesome_flutter: ^10.5.0
  freezed_annotation: ^2.4.1
  go_router: ^11.1.4
  hooks_riverpod: ^2.4.4
  html: ^0.15.4
  http: ^1.1.0
  infinite_scroll_pagination: ^4.0.0
  #yaml: ^3.1.1
  intl: ^0.18.1
  isar: *isar_version
  isar_flutter_libs: *isar_version
  media_kit: ^1.1.8+2
  media_kit_libs_windows_video: ^1.0.9
  media_kit_video: ^1.2.1
  #nirikshak: ^0.1.0
  network_logger:
    git:
      url: https://github.com/themisir/flutter-network-logger.git
      ref: master # branch name
  package_info_plus: ^4.0.2
  path: ^1.8.2
  path_provider: ^2.1.1
  permission_handler: ^10.4.5
  pretty_dio_logger: ^1.3.1
  scroll_to_index: ^3.0.1
  sentry_dio: ^7.10.1
  #copy_with_extension: ^5.0.2
  sentry_flutter: ^7.10.1
  share_plus: ^7.0.2
  shared_preferences: ^2.2.2
  shimmer: ^3.0.0
  sliver_tools: ^0.2.12
  synchronized: ^3.1.0
  timeago: ^3.5.0
  tinycolor2: ^3.0.1
  url_launcher: ^6.1.14
  version: ^3.0.2
  video_player: ^2.7.2
  wakelock_plus: ^1.1.3
  window_manager: ^0.3.7

dev_dependencies:
  build_runner: ^2.4.6
  #copy_with_extension_gen: ^5.0.3
  flutter_lints: ^2.0.3
  freezed: ^2.4.5
  isar_generator: *isar_version

flutter:
  uses-material-design: true
  assets:
    - assets/img/app-logo.png
    #- assets/json/shiki-studios-filtered-sorted.json
    #- .git/
    #- .git/refs/heads/

# Task definition for derry
scripts: derry.yaml
